# change the followings to match your Github username and repo name
baseurl: "/timetravelthree.github.io" # the name of your github repo
url: "https://www.dantexor.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "timetravel3"
description: Blog post of timetravel3

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Simone Petroni
author-bio: Vulnerability Researcher & Reverse Engineer
author-image: bear.jpg # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
  - text: About
    permalink: about
  - text: Bitcoin
    permalink: bitcoin
  - text: Blog
    permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/XorDante
github: https://github.com/timetravelthree
linkedin: https://linkedin.com/in/simone-petroni
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
  - jekyll-seo-tag
