# change the followings to match your Github username and repo name
baseurl: "/cyberdart.github.io" # the name of your github repo
url: "https://blog.cyberdart.eu" # the url of your github pages

# site information used in page title, meta data etc.
title: "cyberdart"
description: Blog post of CyberDart

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# navigation menu
show-nav-menu: true

nav-menu:
  - text: About
    permalink: //cyberdart.eu/about

# use false to turn off any social media links
twitter: https://twitter.com/realcyberdart
github: https://github.com/CyberDart
linkedin: https://linkedin.com/company/cyberdart
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# jekyll plugins - no need to change
plugins:
  - jekyll-seo-tag
